### ISSUE TITLE
Nest Config not obvious

### ISSUE THREAD

**Issue by rtkshmclane** [imbrianj/switchBoard#43]
Brian,

I cannot figure out what to put in my nest config section, beyond user and pass.   I get this error:

/usr/local/src/switchBoard/controllers/nest.js:133
      id = id.replace('00000000-0000-0000-0000-0001000000', '');
              ^
TypeError: Cannot call method 'replace' of undefined
    at Object.module.exports.findLabel (/usr/local/src/switchBoard/controllers/nest.js:133:15)
    at Object.config.callback (/usr/local/src/switchBoard/controllers/nest.js:287:80)
    at IncomingMessage.<anonymous> (/usr/local/src/switchBoard/controllers/nest.js:537:22)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

This is on the first load, as nest is my default screen. 

Second, I have a Yamaha IP connected receiver if you are interested in working on that as well.   I will take a look at the developer section but I am not sure I know enough to code.

-sam

**Comment by imbrianj** [comment]
I believe this should fix that issue, but will need someone to test. https://github.com/imbrianj/switchBoard/commit/3e690531df14a6a8d92e0762936725f3c4962cae

Cleaning up bug queue. #ocd
